// @ts-expect-error - there is a css error
import "./globals.css";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";

import { ThemeProvider } from "@/src/components/ui/theme-provider";
import LeftBar from "@/src/components/layout/LeftBar";
import RightBar from "@/src/components/layout/RightBar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} w-full flex justify-center h-screen overflow-hidden ${geistMono.variable} antialiased`}
      >
        {" "}
        <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          enableSystem
          disableTransitionOnChange
        >
          <div className="hidden sm:block">
            <LeftBar />
          </div>
          <main className="min-w-150 min-h-screen overflow-y-auto">{children}</main>
          <RightBar />
        </ThemeProvider>
      </body>
    </html>
  );
}
